Sitegeist:
  Iconoclasm:


    #
    # The imagemin cli command, you may want to configure an explicit path here for your server
    #
    # The tool can be installed npm install --global imagemin-cli imagemin-pngquant imagemin-webp imagemin-mozjpeg imagemin-svgo
    #
    command: 'imagemin {input} > {output}'

    #
    # The media types that are to be optimized
    #
    # Each media type has to be `enabled` for optimizing. In case specific options or even
    # an different command shall be used the global `command` can be overwritten for each type.
    #
    mediaTypes:
      'image/jpeg':
        enabled: false

      'image/png':
        enabled: false

      'image/webp':
        enabled: false

      'image/gif':
        enabled: false

      'image/svg':
        enabled: false
